name: sba
description: SBA Mobile application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+21

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.3
  get_it: ^7.2.0
  path_provider: ^2.0.8
  equatable: ^2.0.0
  simple_animations: ^5.0.2
  url_launcher: ^6.0.2
  event_bus: ^2.0.0
  keyboard_dismisser: ^3.0.0
  adaptive_dialog: ^1.1.0
  google_maps_flutter: ^2.1.1
  image_picker: ^1.0.2
  dotted_border: ^2.1.0
  form_field_validator: ^1.1.0
  device_info: ^2.0.0
  flutter_spinkit: ^5.0.0
  grouped_list: ^5.1.2
  collection: ^1.15.0
  diacritic: ^0.1.3
  basic_utils: ^5.5.4
  geolocator: ^10.0.0
  hive: ^4.0.0-dev.2
  geocoding: ^2.0.0
  flutter_polyline_points:
    path: flutter_polyline_points
  flutter_slidable: ^3.0.0
  package_info: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  freezed: ^2.1.0+1
  dio:
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  sticky_headers: ^0.3.0+2
  image:
  reorderable_grid_view: ^2.2.2
  flutter_riverpod: ^2.3.10
  lottie: ^2.6.0
  uni_links: ^0.5.1
  fluttertoast: ^8.1.2
  loading_indicator: ^3.1.0
  isar_flutter_libs: ^4.0.0-dev.13
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  local_auth: ^2.1.6
  animated_bottom_navigation_bar: ^1.2.0
  riverpod_annotation:
  riverpod:
  http_parser: ^4.0.2
  mime_type: ^1.0.0
  file_picker: ^6.0.0
  photo_manager: ^3.0.0-dev.5
  synchronized: ^3.1.0
  shimmer: ^3.0.0
  rate_limiter: ^1.0.0
  syncfusion_flutter_signaturepad: ^23.1.44
  google_geocoding_api: ^1.4.1
  intl: ^0.18.1
  syncfusion_flutter_pdfviewer: ^23.2.6
  flutter_inappwebview: ^5.8.0
  photo_view: ^0.14.0
  permission_handler: ^11.0.1
  open_filex: ^4.3.4
  bot_toast: ^4.1.3
  flutter_portal: ^1.1.4
  aad_oauth: ^1.0.0
  vnpt_smartca_module:
    path: vnpt_smartca_module
  jwt_decoder: ^2.0.1
  heif_converter: ^1.0.0

dependency_overrides:
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_gen_runner:
  riverpod_generator:
  json_serializable: ^6.1.6
  freezed_annotation: ^2.1.0
  flutter_lints: ^2.0.3
  grinder: ^0.9.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.8.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/font/
    - assets/json/
    - shorebird.yaml
  fonts:
    - family: Averta
      fonts:
        - asset: fonts/averta_bold.otf
          weight: 800
        - asset: fonts/averta_light.otf
          weight: 300
        - asset: fonts/averta_regular.otf
          weight: 500
        - asset: fonts/averta_light.otf
          weight: 400
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_app.jpg"
  min_sdk_android: 21

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

module:
  androidX: true
